node {
   stage('checkout'){
   echo "git checkout stage"
      git branch: 'main', credentialsId: 'rajendraprasad_github', url: 'https://github.com/rajendraprasad9/bazelbuild.git'
   }
                
   stage('Bazel Build') {
   echo "From Bazel Build Stage"
      sh '''
     cd rules/runfiles
     bazel build //runfiles:execute
      pwd
      ls -l
      '''
   }
   archive('Archive the build') {
   echo "Archive the build"
      archiveArtifacts artifacts: 'cpp-tutorial/stage3/bazel-bin/main', followSymlinks: false, onlyIfSuccessful: true
      
   }
}
