node {
   stage('checkout'){
   echo "git checkout stage"
      git branch: 'main', credentialsId: 'rajendraprasad_github', url: 'https://github.com/rajendraprasad9/bazelbuild.git'
   }
                
   stage('Bazel Build') {
   echo "From Bazel Build Stage"
      sh '''
     cd rules/shell_command
     bazel build //shell_command:rules
      pwd
      ls -l
      '''
   }
}
