node {
   stage('checkout'){
   echo "git checkout stage"
      git branch: 'main', credentialsId: 'rajendraprasad_github', url: 'https://github.com/rajendraprasad9/bazelbuild.git'
   }
                
   stage('Bazel Build') {
   echo "From Bazel Build Stage"
      sh '''
      pwd
      ls
      cd cpp-tutorial/stage3
      bazel build //main:hello-world
      '''
   }
    stage('Archieve Artifact')
      {
         echo "Archieve the Artifact"
         archiveArtifacts artifacts: '/cpp-tutorial/stage3/', followSymlinks: false
      }
    }
